// <auto-generated />
using System;
using GestionInscriptions.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GestionInscriptions.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260109125614_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("GestionInscriptions.Models.AnneeScolaire", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Statut")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("AnneeScolaires");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "2024-2025",
                            Libelle = "Année 2024-2025",
                            Statut = 0
                        },
                        new
                        {
                            Id = 2,
                            Code = "2023-2024",
                            Libelle = "Année 2023-2024",
                            Statut = 1
                        });
                });

            modelBuilder.Entity("GestionInscriptions.Models.Classe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Classes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "L1",
                            Libelle = "Licence 1"
                        },
                        new
                        {
                            Id = 2,
                            Code = "L2",
                            Libelle = "Licence 2"
                        },
                        new
                        {
                            Id = 3,
                            Code = "L3",
                            Libelle = "Licence 3"
                        });
                });

            modelBuilder.Entity("GestionInscriptions.Models.Etudiant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Matricule")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Etudiants");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Matricule = "ETU001",
                            Nom = "Diallo",
                            Prenom = "Mamadou"
                        },
                        new
                        {
                            Id = 2,
                            Matricule = "ETU002",
                            Nom = "Traoré",
                            Prenom = "Fatou"
                        },
                        new
                        {
                            Id = 3,
                            Matricule = "ETU003",
                            Nom = "Sow",
                            Prenom = "Aminata"
                        });
                });

            modelBuilder.Entity("GestionInscriptions.Models.Inscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AnneeScolaireId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClasseId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("EtudiantId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Montant")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AnneeScolaireId");

                    b.HasIndex("ClasseId");

                    b.HasIndex("EtudiantId");

                    b.ToTable("Inscriptions");
                });

            modelBuilder.Entity("GestionInscriptions.Models.Inscription", b =>
                {
                    b.HasOne("GestionInscriptions.Models.AnneeScolaire", "AnneeScolaire")
                        .WithMany("Inscriptions")
                        .HasForeignKey("AnneeScolaireId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GestionInscriptions.Models.Classe", "Classe")
                        .WithMany("Inscriptions")
                        .HasForeignKey("ClasseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GestionInscriptions.Models.Etudiant", "Etudiant")
                        .WithMany("Inscriptions")
                        .HasForeignKey("EtudiantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AnneeScolaire");

                    b.Navigation("Classe");

                    b.Navigation("Etudiant");
                });

            modelBuilder.Entity("GestionInscriptions.Models.AnneeScolaire", b =>
                {
                    b.Navigation("Inscriptions");
                });

            modelBuilder.Entity("GestionInscriptions.Models.Classe", b =>
                {
                    b.Navigation("Inscriptions");
                });

            modelBuilder.Entity("GestionInscriptions.Models.Etudiant", b =>
                {
                    b.Navigation("Inscriptions");
                });
#pragma warning restore 612, 618
        }
    }
}
